### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by Farhad4061**
Applying a license to a repository with an existing license

### CODE REVIEW

**Comment by Farhad4061** [comment]
The open source Ruby gem Licensee](https://github.com/licensee/licensee) compares the repository's *LICENSE* file to a short list of known licenses. Licensee also provides the [Licenses API](/rest/licenses) and [gives us insight into how repositories on {% data variables.product.product_name %} are licensed](https://github.com/blog/1964-open-source-license-usage-on-github-com). If your repository is using a license that isn't listed on the [Choose a License website](https://choosealicense.com/appendix/), you can [request including the license](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license).

If your repository is using a license that is listed on the Choose a License website and it's not displaying clearly at the top of the repository page, it may contain multiple licenses or other complexity. To have your license detected, simplify your *LICENSE* file and note the complexity somewhere else, such as your repository's *README* file

**Comment by Farhad4061** [comment]
Licensing a repository

**Comment by Farhad4061** [comment]
Licensing a repository

**Comment by Arman0916** [comment]
Kya hai ye

**Pull request closed without merging**
